#pragma once

#include <cstddef>
#include <cstring>
#include <limits>
#include <vector>

namespace test {

// Code generated by GPT5-mini with my minor changes.
// Top-k per row (k = 8), CPU reference implementation.
// - input: pointer to row-major matrix [rows x cols]
// - out_vals: pointer to output values buffer [rows x TOPK] (row-major)
// - out_idx:  pointer to output indices buffer [rows x TOPK] (row-major)
// If cols < TOPK, remaining entries are filled with numeric_limits<T>::lowest()
// and index -1.
template <typename T>
inline void refTopK8PerRow(const T* input, int rows, int cols, T* out_vals,
                           int* out_idx, int TOPK) {
  if (rows == 0) return;

  const T neg_inf = std::numeric_limits<T>::lowest();

  for (int r = 0; r < rows; ++r) {
    const T* row = input + r * cols;

    // initialize topk arrays (descending order: largest first)
    std::vector<T> topv(TOPK, 0);
    std::vector<int> topi(TOPK, 0);
    for (int t = 0; t < TOPK; ++t) {
      topv[t] = neg_inf;
      topi[t] = -1;
    }

    // scan row and insert into topk (simple insertion, TOPK small)
    for (int c = 0; c < cols; ++c) {
      const T v = row[c];

      // find insertion position (first position where v > topv[pos])
      int pos = TOPK;
      for (int t = 0; t < TOPK; ++t) {
        if (v > topv[t]) {
          pos = t;
          break;
        }
      }
      if (pos == TOPK) continue;  // not in topk

      // shift down elements to make space
      for (int t = TOPK - 1; t > pos; --t) {
        topv[t] = topv[t - 1];
        topi[t] = topi[t - 1];
      }

      // write new element
      topv[pos] = v;
      topi[pos] = static_cast<int>(c);
    }

    // store results into output buffers
    T* outv_row = out_vals + r * TOPK;
    int* outi_row = out_idx + r * TOPK;
    for (int t = 0; t < TOPK; ++t) {
      outv_row[t] = topv[t];
      outi_row[t] = topi[t];
    }
  }
}

}  // namespace test