name: Flash MOE CI
run-name: Run All Tests
on: [push, workflow_dispatch]

jobs:
  Run-all-tests:
    uses: makora-ai/CI_setup_test_project/.github/workflows/build-docker-and-run-script-rw.yml@main
    with:
      docker-image-name: ci_image_rocm_7_0_vllm_0_11_2
      script-path: ./scripts/buildAndRun.sh
      registry-port: 5001
      run-mi250-jobs: false